# Generated by Django 4.2 on 2024-05-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
