# Generated by Django 4.2 on 2024-05-06 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inmueble_imagen_alter_inmueble_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo_de_inmueble',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
