# Generated by Django 4.2 on 2024-05-06 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_inmueble_tipo_de_inmueble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], default='hola', max_length=12),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
    ]
