# Generated by Django 4.2 on 2024-05-06 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inmueble_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles_propiedad', to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_de_inmueble',
            field=models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('parcela', 'Parcela')], max_length=12),
        ),
    ]
